function [tau_cmg1, tau_cmg2] = CMG(gyro1, gyro2, contpar, state)
% CMG.m
% This script calculates the torques generated by the Control Moment
% Gyroscopes (CMGs) on the Autonomous Underwater Vehicle (AUV). The torques
% are derived based on the current angular velocities, the CMG deflection
% angles, and the gyroscope properties. The script accounts for gyroscopic
% effects in all three rotational axes (roll, pitch, and yaw).
%
% Inputs
% - gyro1, gyro2: Structures containing the properties of each gyroscope,
%                 including their moments of inertia (I).
% - contpar: Structure containing control parameters, such as angular
%            accelerations for each CMG's flywheel and gimbal.
% - state: Current state vector of the vehicle, including angular
%          velocities (p, q, r) and CMG states (deflection angles and
%          flywheel angular velocities).
%
% Outputs
% - tau_cmg1, tau_cmg2: Structures containing the calculated torques (K, M, N)
%                       for each CMG in N*m, representing the torques around
%                       the roll, pitch, and yaw axes.

%% VARIABLES
% Extract vehicle angular velocities around the roll, pitch, and yaw axes
p       = state(10);  % Roll rate
q       = state(11);  % Pitch rate
r       = state(12);  % Yaw rate

% Extract state variables for the aft and forward CMGs
% Deflection angle (gimbal angle) and flywheel angular velocity for CMG #1 (aft)
alpha1  = state(13);    
Omega1  = state(14);    

% Deflection angle (gimbal angle) and flywheel angular velocity for CMG #2 (forward)
alpha2  = state(15);    
Omega2  = state(16);    

% Moments of inertia for each CMG
I1      = gyro1.I;
I2      = gyro2.I;

% Extract control parameters for each CMG
% These include the rate of change of deflection angle (alphadot) and
% flywheel angular acceleration (Omegadot) for each CMG
alphadot1 = contpar.alphadot1;  % Gimbal angular velocity for CMG #1
Omegadot1 = contpar.Omegadot1;  % Flywheel angular acceleration for CMG #1
alphadot2 = contpar.alphadot2;  % Gimbal angular velocity for CMG #2
Omegadot2 = contpar.Omegadot2;  % Flywheel angular acceleration for CMG #2

%% CMG RIGID BODY DYNAMICS
% Calculate the torques generated by each CMG on the roll (K), pitch (M),
% and yaw (N) axes. These torques are caused by gyroscopic effects and are
% influenced by the deflection angles, flywheel speeds, and angular velocities.

% AFT CMG (CMG #1)
% Roll torque (tau_cmg1.K) generated by CMG #1
% Includes contributions from the gimbal angle (alpha1), flywheel speed (Omega1),
% gimbal angular velocity (alphadot1), and flywheel acceleration (Omegadot1)
tau_cmg1.K  = -I1 * (cos(alpha1) * Omega1 * alphadot1 + sin(alpha1) * Omegadot1 + cos(alpha1) * Omega1 * r);

% Pitch torque (tau_cmg1.M) generated by CMG #1
% Similarly influenced by the gyroscopic properties and vehicle dynamics
tau_cmg1.M  = -I1 * (sin(alpha1) * Omega1 * alphadot1 - cos(alpha1) * Omegadot1 + sin(alpha1) * Omega1 * r);

% Yaw torque (tau_cmg1.N) generated by CMG #1
% Affected by the roll and pitch rates (p, q) and the flywheel speed (Omega1)
tau_cmg1.N  = I1 * Omega1 * (cos(alpha1) * p + sin(alpha1) * q);

% FWD CMG (CMG #2)
% Roll torque (tau_cmg2.K) generated by CMG #2
% Calculated similarly to CMG #1 but using the parameters for CMG #2
tau_cmg2.K  = -I2 * (cos(alpha2) * Omega2 * alphadot2 + sin(alpha2) * Omegadot2 + cos(alpha2) * Omega2 * r);

% Pitch torque (tau_cmg2.M) generated by CMG #2
% Accounts for the gyroscopic effects based on CMG #2's properties
tau_cmg2.M  = -I2 * (sin(alpha2) * Omega2 * alphadot2 - cos(alpha2) * Omegadot2 + sin(alpha2) * Omega2 * r);

% Yaw torque (tau_cmg2.N) generated by CMG #2
% Influenced by the vehicle's roll and pitch rates (p, q) and the flywheel speed (Omega2)
tau_cmg2.N  = I2 * Omega2 * (cos(alpha2) * p + sin(alpha2) * q);

end