function [tau_cmg1,tau_cmg2] = CMG(gyro1,gyro2,contpar,state)
% CMG.m
% This script calculates the torques generated by the Control Moment
% Gyroscope (CMG) on the Autonomous Underwater Vehicle (AUV). The torques
% are derived based on the current angular velocities, the CMG deflection
% angle, and the gyroscope's properties. The script accounts for the
% gyroscopic effects in all three rotational axes (roll, pitch, and yaw).
% 
% Inputs
% - gyro: Structure containing the gyroscope's properties, including
% inertia.
% - contpar: Structure containing control parameters, including angular
% accelerations.
% - state: Current state vector of the vehicle, including angular
% velocities and CMG states.
% 
% Outputs
% - tau_cmg: Structure containing the calculated torques (K, M, N) in N*m,
% representing the roll, pitch, and yaw torques generated by the CMG.

%% VARIABLES
p           = state(10);
q           = state(11);
r           = state(12);
alpha1      = state(13);    
Omega1      = state(14);    
alpha2      = state(15);    
Omega2      = state(16); 

I1          = gyro1.I;
I2          = gyro2.I;

alphadot1   = contpar.alphadot1;
Omegadot1   = contpar.Omegadot1;
alphadot2   = contpar.alphadot2;
Omegadot2   = contpar.Omegadot2;

%% CMG RIGID BODY DYNAMICS
% AFT CMG (CMG #1)
tau_cmg1.K  = -I1*(cos(alpha1)*Omega1*alphadot1 + sin(alpha1)*Omegadot1 + cos(alpha1)*Omega1*r);
tau_cmg1.M  = -I1*(sin(alpha1)*Omega1*alphadot1 - cos(alpha1)*Omegadot1 + sin(alpha1)*Omega1*r);
tau_cmg1.N  = I1*Omega1*(cos(alpha1)*p + sin(alpha1)*q);

% FWD CMG (CMG #2)
tau_cmg2.K  = -I2*(cos(alpha2)*Omega2*alphadot2 + sin(alpha2)*Omegadot2 + cos(alpha2)*Omega2*r);
tau_cmg2.M  = -I2*(sin(alpha2)*Omega2*alphadot2 - cos(alpha2)*Omegadot2 + sin(alpha2)*Omega2*r);
tau_cmg2.N  = I2*Omega2*(cos(alpha2)*p + sin(alpha2)*q);

end