function [tau_cmg] = CMG(gyro,contpar,state)
% CMG.m
% This script calculates the torques generated by the Control Moment
% Gyroscope (CMG) on the Autonomous Underwater Vehicle (AUV). The torques
% are derived based on the current angular velocities, the CMG deflection
% angle, and the gyroscope's properties. The script accounts for the
% gyroscopic effects in all three rotational axes (roll, pitch, and yaw).
% 
% Inputs
% - gyro: Structure containing the gyroscope's properties, including
% inertia.
% - contpar: Structure containing control parameters, including angular
% accelerations.
% - state: Current state vector of the vehicle, including angular
% velocities and CMG states.
% 
% Outputs
% - tau_cmg: Structure containing the calculated torques (K, M, N) in N*m,
% representing the roll, pitch, and yaw torques generated by the CMG.

%% VARIABLES
p           = state(10);
q           = state(11);
r           = state(12);
alpha       = state(13);    
Omega       = state(14);    

I           = gyro.I;

alphadot    = contpar.alphadot;
Omegadot    = contpar.Omegadot;

%% CMG RIGID BODY DYNAMICS
tau_cmg.K   = -I*(cos(alpha)*Omega*alphadot + sin(alpha)*Omegadot + cos(alpha)*Omega*r);
tau_cmg.M   = -I*(sin(alpha)*Omega*alphadot - cos(alpha)*Omegadot + sin(alpha)*Omega*r);
tau_cmg.N   = I*Omega*(cos(alpha)*p + sin(alpha)*q);
end