% COMPARE_CMG_BASELINES.m
% Compare saved single- and symmetric dual-CMG VFR baseline results.

clearvars;
scriptDir = fileparts(mfilename('fullpath'));
single = load(fullfile(scriptDir, 'Working Results', 'single', 'VFR', ...
    'simulation_result.mat'));
dual = load(fullfile(scriptDir, 'Working Results', 'dual', ...
    'symmetric_spin', 'VFR', 'simulation_result.mat'));

metric = @(result) struct( ...
    'settlingTime', result.simSummary.settlingTime2Percent, ...
    'overshootPercent', result.simSummary.rollOvershootPercent, ...
    'finalErrorDeg', rad2deg(result.simSummary.finalRollError), ...
    'rollMomentRMSE', result.simSummary.rollMomentRMSE, ...
    'peakGimbalRate', max(result.simSummary.peakGimbalRate), ...
    'peakGimbalAccel', max(result.simSummary.peakGimbalAccel), ...
    'gimbalExcursionDeg', rad2deg(max(result.simSummary.gimbalExcursion)), ...
    'peakPitchDeg', rad2deg(result.simSummary.maxAbsPitch), ...
    'peakYawDeg', rad2deg(result.simSummary.maxAbsYaw), ...
    'idealManeuverInput', result.energy.input.idealSystemGross, ...
    'initialStoredSpinEnergy', result.energy.storedInitial.total, ...
    'idealInputIncludingSpinup', ...
        result.energy.input.idealSystemGrossIncludingSpinup, ...
    'idealIncludingSpinupPercent', ...
        result.energy.efficiency.idealIncludingSpinupPercent);

comparison.single = metric(single);
comparison.dual = metric(dual);
comparison.dual.initialRotorSpeedRpm = ...
    abs(dual.Y_OUT(1,14))*60/(2*pi);
comparison.dual.maximumConditionNumber = dual.simSummary.maxConditionNumber;
comparison.dual.maximumSolveResidual = dual.simSummary.maxSolveResidual;
comparison.dual.nearSingularSamples = nnz(dual.controlHistory.nearSingularity);

fprintf('\nSingle versus dual CMG VFR baseline\n');
fprintf('                         Single          Dual\n');
fprintf('Settling time (s)       %8.4f      %8.4f\n', ...
    comparison.single.settlingTime, comparison.dual.settlingTime);
fprintf('Overshoot (%%)           %8.4f      %8.4f\n', ...
    comparison.single.overshootPercent, comparison.dual.overshootPercent);
fprintf('Final error (deg)       %8.4f      %8.4f\n', ...
    comparison.single.finalErrorDeg, comparison.dual.finalErrorDeg);
fprintf('Roll RMSE (N m)         %8.4f      %8.4f\n', ...
    comparison.single.rollMomentRMSE, comparison.dual.rollMomentRMSE);
fprintf('Peak gimbal rate        %8.4f      %8.4f rad/s\n', ...
    comparison.single.peakGimbalRate, comparison.dual.peakGimbalRate);
fprintf('Peak pitch (deg)        %8.4f      %8.4f\n', ...
    comparison.single.peakPitchDeg, comparison.dual.peakPitchDeg);
fprintf('Peak yaw (deg)          %8.4f      %8.4f\n', ...
    comparison.single.peakYawDeg, comparison.dual.peakYawDeg);
fprintf('Gimbal excursion (deg)  %8.4f      %8.4f\n', ...
    comparison.single.gimbalExcursionDeg, ...
    comparison.dual.gimbalExcursionDeg);
fprintf('Ideal maneuver input J  %8.4f      %8.4f\n', ...
    comparison.single.idealManeuverInput, ...
    comparison.dual.idealManeuverInput);
fprintf('Initial spin energy J   %8.4f      %8.4f\n', ...
    comparison.single.initialStoredSpinEnergy, ...
    comparison.dual.initialStoredSpinEnergy);
fprintf('Input incl. spin-up J   %8.4f      %8.4f\n', ...
    comparison.single.idealInputIncludingSpinup, ...
    comparison.dual.idealInputIncludingSpinup);

comparison.change.dualSettlingTimePercent = 100*( ...
    comparison.dual.settlingTime/comparison.single.settlingTime-1);
comparison.change.dualPeakGimbalRatePercent = 100*( ...
    comparison.dual.peakGimbalRate/comparison.single.peakGimbalRate-1);
comparison.change.dualGimbalExcursionPercent = 100*( ...
    comparison.dual.gimbalExcursionDeg ...
    /comparison.single.gimbalExcursionDeg-1);
comparison.change.dualInputIncludingSpinupPercent = 100*( ...
    comparison.dual.idealInputIncludingSpinup ...
    /comparison.single.idealInputIncludingSpinup-1);

fig = figure('Name', 'Single versus dual CMG baseline');
tiledlayout(2,2, 'TileSpacing', 'compact');
nexttile;
plot(single.T_OUT, rad2deg(single.Y_OUT(:,4)), 'LineWidth', 2);
hold on;
plot(dual.T_OUT, rad2deg(dual.Y_OUT(:,4)), '--', 'LineWidth', 2);
yline(90, ':k');
hold off;
xlabel('Time (s)'); ylabel('Roll (deg)'); grid on;
legend('Single','Dual','Target','Location','best');
title('Roll response');
nexttile;
plot(single.T_OUT, single.controlHistory.alphadot(:,1), 'LineWidth', 2);
hold on;
plot(dual.T_OUT, dual.controlHistory.alphadot, '--', 'LineWidth', 1.5);
hold off;
xlabel('Time (s)'); ylabel('Gimbal rate (rad/s)'); grid on;
legend('Single 1','Dual 1','Dual 2','Location','best');
title('Gimbal rates');
nexttile;
plot(single.T_OUT, rad2deg(single.Y_OUT(:,5:6)), 'LineWidth', 2);
hold on;
plot(dual.T_OUT, rad2deg(dual.Y_OUT(:,5:6)), '--', 'LineWidth', 1.5);
hold off;
xlabel('Time (s)'); ylabel('Angle (deg)'); grid on;
legend('Single pitch','Single yaw','Dual pitch','Dual yaw', ...
    'Location','best');
title('Cross-axis response');
nexttile;
bar([comparison.single.idealManeuverInput, ...
     comparison.single.idealInputIncludingSpinup; ...
     comparison.dual.idealManeuverInput, ...
     comparison.dual.idealInputIncludingSpinup]);
set(gca, 'XTickLabel', {'Single','Dual'});
ylabel('Ideal energy proxy (J)'); grid on;
legend('Maneuver only','Including initial spin','Location','best');
title('Energy accounting');
exportgraphics(fig, fullfile(scriptDir, 'Working Results', ...
    'CMG_BASELINE_COMPARISON.png'), 'Resolution', 300);

save(fullfile(scriptDir, 'Working Results', 'cmg_baseline_comparison.mat'), ...
    'comparison');
